### PR TITLE
Merchant statistics

### PR DESCRIPTION
**Pull request by maddyg91**
All statistics done. 
Tests passing.

### CODE REVIEW

**Comment by bendelonlee** [comment]
Here's the story:

As a visitor
When I visit the merchants index page, I see an area with statistics:
- top 3 merchants who have sold the most by price and quantity. Check, check
- top 3 merchants who were fastest at fulfilling items in an order. check
- worst 3 merchants who were slowest at fulfilling items in an order. check
- top 3 states where any orders were shipped. check
- top 3 cities where any orders were shipped (Springfield, MI should not be grouped with Springfield, CO). check
- top 3 biggest orders by quantity of items. check

**Comment by bendelonlee** [comment]
@iandouglas 
I’m reviewing Maddie’s PR for merchant index statistics. Two things:
1) Top merchant by price. She seems to be summing the price of all their order items… To me, this could be valid interpretation of top merchant by price, but I’m not sure. The user story doesn’t say top merchant by revenue. It says top merchant by price and I’m not very clear on what that means. (I would ask her if she cleared this with you, but she is busy parenting at the moment)

**Comment by iandouglas** [comment]
"top 3 merchants who have sold the most by price and quantity" -- I've revised this for next inning to be more clear that these are the top 3 merchants by revenue, which is a multiplication of price and quantity, not two separate statistics. If @maddyg91 built this as two different stats, that's okay, since this version of the user story isn't clear.

**Comment by bendelonlee** [comment]
Thanks for letting us know!

**Comment by bendelonlee** [comment]
Merge with master caused a lot of failing tests. Decided to revert

**Pull request merged**
