### PR TITLE
Boosting coverage

### PR DESCRIPTION
**Pull request by jpclark6**
Coverage now 100%. Minor refactoring on some style. Titleizes all item names and merchant names.

### CODE REVIEW

**Comment by bendelonlee** [comment]
I added tests for percent to be 0 and 100. Also, though I appreciated total items returning infinity instead of zero for division purposes, it bothered me that if you hadn’t sold anything but had items in stock, it would return infinity. So I refactored the method a bit.

**Comment by jpclark6** [comment]
Mainly on those the only place total_items is ever called is from percent_items_sold, but I see what you're saying. Do you want someone else to merge now, or do you still want to?

**Comment by bendelonlee** [comment]
This seems good to merge.

**Comment by bendelonlee** [comment]
I'm not really sure.

**Pull request merged**
